version: '3.8'

services:
  streamlit:
    build: .
    extra_hosts:
    - "host.docker.internal:host-gateway"
    ports:
      - "8501:8501"
    volumes:
      - streamlit:/data/streamlit
    depends_on:
      - postgres
      
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DATABASE: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "5050:80"
    restart: always


networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  streamlit:
  pgAdmin:
