version: '3.9'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/datas
    volumes:
       - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "5050:80"
    volumes:
      - pgadmin:/var/lib/pgadmin/data
    depends_on:
      - postgres 
    links:
      - "postgres"

  metabase:
    container_name: metabase_container
    image: metabase/metabase:latest
    environment:
       MB_DB_TYPE: postgres
       MB_DB_DBNAME: postgres
       MB_DB_PORT: 5432
       MB_DB_USER: postgres
       MB_DB_PASS: postgres
       MB_DB_HOST: 192.168.96.2
    volumes:
      - metabase:/var/lib/metabase/data
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - postgres
    links:
      - "postgres"
    networks:
      - postgres



networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  metabase:
